### ISSUE TITLE
loggregator failing - dea_logging_agent not able to connect to warden logs [v160 & v161]

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/dea_ng#109]
Instead of seeing lovely loggregator output during a `cf push` like:

```
Starting app env in org starkandwayne / space development as drnicwilliams@gmail.com...
OK
-----> Downloaded app package (240K)
 !
 !     Gemfile.lock required. Please check it in.
 !
```

Instead, we're seeing this nebulous error:

```
Starting app env in org me / space test as admin...
OK

FAILED
Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed
```

Looking through the dea logs, we see the following:

```
==> /var/vcap/sys/log/dea_logging_agent/dea_logging_agent.stdout.log <==
{"timestamp":1393890563.089097738,"process_id":2454,"source":"deaagent","log_level":"info","message":"Removing stale task /var/vcap/data/warden/depot/17jnev56eht/jobs/71","data":null,"file":"/var/vcap/data/compile/dea_logging_agent/loggregator/src/deaagent/agent.go","line":50,"method":"deaagent.func·001"}
{"timestamp":1393890563.121195793,"process_id":2454,"source":"deaagent","log_level":"info","message":"Error while reading from socket ERR, /var/vcap/data/warden/depot/17jnev56eht/jobs/71, EOF","data":null,"file":"/var/vcap/data/compile/dea_logging_agent/loggregator/src/deaagent/logging_stream.go","line":118,"method":"deaagent.func·006"}
{"timestamp":1393890563.121331453,"process_id":2454,"source":"deaagent","log_level":"info","message":"Stopped reading from socket ERR, /var/vcap/data/warden/depot/17jnev56eht/jobs/71","data":null,"file":"/var/vcap/data/compile/dea_logging_agent/loggregator/src/deaagent/logging_stream.go","line":76,"method":"deaagent.func·005"}
{"timestamp":1393890563.121397734,"process_id":2454,"source":"deaagent","log_level":"info","message":"Error while reading from socket OUT, /var/vcap/data/warden/depot/17jnev56eht/jobs/71, EOF","data":null,"file":"/var/vcap/data/compile/dea_logging_agent/loggregator/src/deaagent/logging_stream.go","line":118,"method":"deaagent.func·006"}
{"timestamp":1393890563.121475220,"process_id":2454,"source":"deaagent","log_level":"info","message":"Stopped reading from socket OUT, /var/vcap/data/warden/depot/17jnev56eht/jobs/71","data":null,"file":"/var/vcap/data/compile/dea_logging_agent/loggregator/src/deaagent/logging_stream.go","line":76,"method":"deaagent.func·005"}
```

This is on an AWS VPC deployment (from scratch). @frodenas mentioned that he's also seeing this on an OpenStack deployment.

The same app (set to fail, without the Gemfile.lock) is working on run.pivotal.io; as per the example at the top.

When the Gemfile.lock is present in the app, and the deployment succeeds, then we still don't see loggregator logs - but the app works. So this bug is not affecting deployment of apps.

Both the AWS & OpenStack deployments which see this issue are using "http" rather than "https".

The `properties.dea_next` section of the manifest looks like:

``` yaml
  dea_next:
    allow_networks:
    - 10.10.0.2/32
    deny_networks:
    - 169.254.0.0/16
    - 10.10.0.0/24
    - 10.10.16.0/20
    - 10.10.80.0/20
    directory_server_protocol: http
    disk_mb: 102400
    disk_overcommit_factor: 2
    evacuation_bail_out_time_in_seconds: 600
    instance_disk_inode_limit: 200000
    kernel_network_tuning_enabled: true
    memory_mb: 15000
    memory_overcommit_factor: 3
    staging_disk_inode_limit: 200000
```
